# Generated by Django 4.1.4 on 2022-12-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('overall', models.IntegerField(default=0)),
                ('born_year', models.DateField()),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('body', models.IntegerField()),
                ('skill', models.IntegerField(default=1)),
                ('left_foot', models.IntegerField()),
                ('right_foot', models.IntegerField()),
            ],
        ),
    ]
